plugins {
    id 'com.android.application'
}

android {
    namespace 'com.boox.firefoxscroll'
    compileSdk 33

    defaultConfig {
        applicationId 'com.boox.firefoxscroll.boox12'
        minSdk 23
        targetSdk 33
        versionCode 3
        versionName '1.0.2-boox12'
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            signingConfig signingConfigs.debug
        }
    }
}
